version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"