from dataclasses import dataclass
from typing import Any, Dict, List, Literal, Mapping, Optional

from .user import UserShortDetails


@dataclass
class DomainInEndpoint:
    protocol: str
    name: str
    id: str


@dataclass
class EndpointHardwareInstanceDetails:
    id: str
    name: str


@dataclass
class EndpointAutogeneratedHFModelDetails:
    id: str
    keyId: Optional[str]


@dataclass
class EndpointAutogeneratedOutpostModelDetails:
    fullName: str


# used for response parsing
class EndpointAutogeneratedTemplateConfigDetails:
    config: Optional[Dict[str, Any]] = None
    revision: Optional[str] = None
    modelSource: Literal["huggingface", "outpost"]
    huggingfaceModel: Optional[EndpointAutogeneratedHFModelDetails] = None
    outpostModel: Optional[EndpointAutogeneratedOutpostModelDetails] = None

    def __init__(self, *args, **kwargs) -> None:
        for field in self.__annotations__:
            if field == "outpostModel" and kwargs.get("outpostModel") is not None:
                self.outpostModel = EndpointAutogeneratedOutpostModelDetails(
                    **kwargs.get("outpostModel")
                )
            elif (
                field == "huggingfaceModel"
                and kwargs.get("huggingfaceModel") is not None
            ):
                self.huggingfaceModel = EndpointAutogeneratedHFModelDetails(
                    **kwargs.get("huggingfaceModel")
                )
            else:
                setattr(self, field, kwargs.get(field))


# used for creation
class EndpointAutogeneratedTemplateConfig:
    config: Optional[Dict[str, Any]] = None
    revision: Optional[str] = None
    modelSource: Literal["huggingface", "outpost"]
    huggingfaceModel: Optional[EndpointAutogeneratedHFModelDetails] = None
    outpostModel: Optional[EndpointAutogeneratedOutpostModelDetails] = None


@dataclass
class EndpointCustomTemplateConfig:
    type: Literal["file", "url"]
    className: str
    path: str


@dataclass
class EndpointCustomTemplateConfigDetails:
    type: Literal["file", "url"]
    url: Optional[str]
    className: str


@dataclass
class EndpointDeployment:
    id: str
    status: str
    createdAt: str
    concludedAt: Optional[str]
    updatedAt: str
    timeTakenS: Optional[int]
    creator: Optional[UserShortDetails]

    def __init__(self, *args, **kwargs) -> None:
        for field in self.__annotations__:
            if field == "creator" and kwargs.get("creator") is not None:
                self.creator = UserShortDetails(**kwargs.get("creator"))
            else:
                setattr(self, field, kwargs.get(field))


@dataclass
class ReplicaScalingConfig:
    min: int
    max: int
    scaledownPeriod: int
    targetPendingRequests: int

    def __init__(self, *args, **kwargs) -> None:
        for field in self.__annotations__:
            setattr(self, field, kwargs.get(field))


@dataclass
class EndpointResource:
    """
    A Endpoint Service on Outpost.
    """

    fullName: str
    """The fullName used to identify the endpoint service."""

    name: str
    """Name of the endpoint service."""

    visibility: Literal["public", "private", "internal"]
    """Name of the endpoint service."""

    id: str
    """ID of the endpoint service."""

    ownerId: str
    """Owner of the endpoint service."""

    containerType: Literal["custom", "prebuilt"]
    """Container type of the endpoint service."""

    templateType: Literal["autogenerated", "custom"]
    """type of template to be used for the endpoint server."""

    autogeneratedTemplateConfig: Optional[EndpointAutogeneratedTemplateConfigDetails]
    """configs to autogenerate template."""

    customTemplateConfig: Optional[EndpointCustomTemplateConfigDetails]
    """custom template details."""

    taskType: str
    """Task type of the endpoint service."""

    config: dict
    """Config of the endpoint service."""

    predictionPath: str
    """Relative path used for prediction and target for scaling."""

    healthcheckPath: str
    """Relative path used for healthcheck and readiness probes"""

    primaryDomain: Optional[DomainInEndpoint]

    createdAt: str

    updatedAt: str

    status: str

    hardwareInstance: EndpointHardwareInstanceDetails

    port: int

    internalDomains: List[Dict[str, Any]]

    # creatorId: Optional[str]=None

    # currentDeploymentId: Optional[str]=None

    currentDeployment: Optional[EndpointDeployment] = None

    # thirdPartyKeyId: Optional[str] =None

    # configSchema: Optional[str] =None

    replicaScalingConfig: Optional[ReplicaScalingConfig] = None

    def __init__(self, *args, **kwargs: Mapping[str, Any]) -> None:
        for field in self.__annotations__:
            if (
                field == "autogeneratedTemplateConfig"
                and kwargs.get("autogeneratedTemplateConfig") is not None
            ):
                self.autogeneratedTemplateConfig = (
                    EndpointAutogeneratedTemplateConfigDetails(
                        **kwargs.get("autogeneratedTemplateConfig")
                    )
                )
            elif (
                field == "customTemplateConfig"
                and kwargs.get("customTemplateConfig") is not None
            ):
                self.customTemplateConfig = EndpointCustomTemplateConfigDetails(
                    **kwargs.get("customTemplateConfig")
                )
            elif field == "primaryDomain" and kwargs.get("primaryDomain") is not None:
                self.primaryDomain = DomainInEndpoint(**kwargs.get("primaryDomain"))
            elif field == "hardwareInstance":
                self.hardwareInstance = EndpointHardwareInstanceDetails(
                    **kwargs.get("hardwareInstance")
                )
            elif (
                field == "currentDeployment"
                and kwargs.get("currentDeployment") is not None
            ):
                self.currentDeployment = EndpointDeployment(
                    **kwargs.get("currentDeployment")
                )
            elif (
                field == "replicaScalingConfig"
                and kwargs.get("replicaScalingConfig") is not None
            ):
                self.replicaScalingConfig = ReplicaScalingConfig(
                    **kwargs.get("replicaScalingConfig")
                )
            else:
                setattr(self, field, kwargs.get(field))

@dataclass
class EndpointReplicaStatusCondition:
    lastTransitionTime: str
    lastUpdateTime: str
    message: str
    reason: str
    status: str
    type: str


@dataclass
class EndpointReplicaStatus:
    conditions: Optional[List[EndpointReplicaStatusCondition]] = []
    observedGeneration: Optional[int] = None
    availableReplicas: Optional[int] = None
    readyReplicas: Optional[int] = None
    replicas: Optional[int] = None
    unavailableReplicas: Optional[int] = None
    updatedReplicas: Optional[int] = None

    def __init__(self, *args, **kwargs) -> None:
        for field in self.__annotations__:
            if field == "condition" and kwargs.get("conditions") is not None:
                self.outpostModel = EndpointReplicaStatusCondition(
                    **kwargs.get("condition")
                )
            else:
                setattr(self, field, kwargs.get(field))
