from typing import Optional

from outpostkit._types.endpoint import (
    EndpointAutogeneratedHFModelDetails,
    EndpointAutogeneratedTemplateConfig,
)
from outpostkit._utils.constants import OutpostSecret
from outpostkit.client import Client
from outpostkit.endpoints import Endpoints

API_TOKEN: str = "<api-token>"
HF_TOKEN: Optional[str] = None
ENTITY: str = "katara-murphy"
template = EndpointAutogeneratedTemplateConfig(
    modelSource="huggingface",
    huggingfaceModel=EndpointAutogeneratedHFModelDetails(
        id="nomic-ai/nomic-embed-text-v1",
    ),
)

endpt = Endpoints(client=Client(api_token=API_TOKEN), entity=ENTITY).create(
    template=template,
    name="text-embedder",
    hardware_instance="1xnvidia-tesla-t4",
    secrets=[OutpostSecret(name="HUGGING_FACE_HUB_TOKEN", value=HF_TOKEN)]
    if HF_TOKEN
    else None,
)
endpt.deploy()


# wait for endpoint to start.

if endpt.get().status == "healthy":
    predictor = endpt.create_predictor()
    predictor.infer(json={"sentences": "hello."})
