from outpostkit.client import Client

a = Client(api_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJscWl1eGpqNm9rYnp0NzJqMWV5azV2bjIiLCJ0eXBlIjoibG9naW4iLCJpYXQiOjE3MDY2MDg2MjMsImV4cCI6MTcwOTIwMDYyMiwianRpIjoiY2xzMDZwbGlqMDAwdGdvMDlpN2h6dHRxMSJ9.lM94riqe5MQ6egJ7nqpDNCbmwpwqeFr_q-M1yrmenUI")

print(a.user)
